# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"open_file": "00_municipal_analytics.ipynb",
         "UrbanMunicipalMarketPrices": "00_municipal_analytics.ipynb",
         "UrbanMunicipalMarketPricesFactory": "00_municipal_analytics.ipynb",
         "run": "00_municipal_analytics.ipynb",
         "main": "00_municipal_analytics.ipynb"}

modules = ["urban_municipal_analytics.py"]

doc_url = "https://epocolis.github.io/urban_municipal_data_cleaner/"

git_url = "https://github.com/epocolis/urban_municipal_data_cleaner/tree/main/"

def custom_doc_links(name): return None
