# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Constants": "00_retail_price_analytics.ipynb",
         "is_row_not_empty": "00_retail_price_analytics.ipynb",
         "convert_list_to_dict": "00_retail_price_analytics.ipynb",
         "RetailPricesAnalyzer": "00_retail_price_analytics.ipynb",
         "open_file": "00_retail_price_analytics.ipynb",
         "run": "00_retail_price_analytics.ipynb",
         "main": "00_retail_price_analytics.ipynb"}

modules = ["retail_price_analytics.py"]

doc_url = "https://epocolis.github.io/retail_price_analytics/"

git_url = "https://github.com/epocolis/retail_price_analytics/tree/master/"

def custom_doc_links(name): return None
