# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"not_empty": "farmgate_data_viz.ipynb",
         "remove_brand_row": "farmgate_data_viz.ipynb",
         "get_parishes": "farmgate_data_viz.ipynb",
         "remove_empty_strings_from_data_rows": "farmgate_data_viz.ipynb",
         "get_data": "farmgate_data_viz.ipynb",
         "format_date": "farmgate_data_viz.ipynb",
         "get_headers": "farmgate_data_viz.ipynb",
         "clean_date": "farmgate_data_viz.ipynb",
         "s": "farmgate_data_viz.ipynb",
         "ParishData": "farmgate_data_viz.ipynb",
         "flatten_list": "farmgate_data_viz.ipynb",
         "remove_empty_strings_from_list": "farmgate_data_viz.ipynb",
         "create_parish_data": "farmgate_data_viz.ipynb",
         "split_data": "farmgate_data_viz.ipynb",
         "process_group": "farmgate_data_viz.ipynb",
         "group": "farmgate_data_viz.ipynb",
         "header": "farmgate_data_viz.ipynb",
         "run": "farmgate_data_viz.ipynb",
         "main": "farmgate_data_viz.ipynb"}

modules = ["agricultural_pricing_analytics.py"]

doc_url = "https://epocolis.github.io/farm_analytics/"

git_url = "https://github.com/epocolis/farm_analytics/tree/master/"

def custom_doc_links(name): return None
