# AUTOGENERATED! DO NOT EDIT! File to edit: price_analytics.ipynb (unless otherwise specified).

__all__ = ['food_price_analytics', 'type']

# Cell
#hide
import sys
from nbdev.showdoc import *
from nbdev.export import notebook2script
import pandas as pd
from fastcore.script import *
import click
from .farm_gate_price_processor import process_farm_gate_data
from .wholesale_price_processor import process_wholesale_price_data
from .urban_municipal_price_processor import process_municipal_price_data
from .retail_price_processor import process_retail_price_data



# Cell
@click.command()
@click.option('-t', "--data-type",
type=click.Choice(['farmgate','retail','markets','wholesale']), required=True)
@click.argument('input_file', required=True,type=str)
@click.argument('output_directory', required=True, type=str)
def food_price_analytics(data_type,input_file, output_directory):

    "Clean up the input file and generates individual parish farm gate prices in the specified output folder"
    print(f"input path:{input_file}")
    print(f"output_directory:{output_directory}")
    print(f"data type {data_type}")
    if data_type.lower() == "farmgate":
        print("running farmgate")
        process_farm_gate_data(input_file, output_directory)
    if data_type.lower() == "retail":
        process_retail_price_data(input_file,output_directory)
        return
    if data_type.lower() == "markets":
        process_municipal_price_data(input_file,output_directory)
        return
    if data_type.lower() == "wholesale":
        process_wholesale_price_data(input_file,output_directory)
        return

    print("You entered and invalid dataype option")
    sys.exit(-1)