# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_header": "00_wholesale_price_analytics.ipynb",
         "remove_empty_items": "00_wholesale_price_analytics.ipynb",
         "remove_surrounding_spaces_from_items": "00_wholesale_price_analytics.ipynb",
         "get_data": "00_wholesale_price_analytics.ipynb",
         "write_to_csv": "00_wholesale_price_analytics.ipynb",
         "get_report_date": "00_wholesale_price_analytics.ipynb",
         "run": "00_wholesale_price_analytics.ipynb",
         "main": "00_wholesale_price_analytics.ipynb"}

modules = ["wholesale_price_analytics.py"]

doc_url = "https://epocolis.github.io/wholesale_price_analytics/"

git_url = "https://github.com/epocolis/wholesale_price_analytics/tree/main/"

def custom_doc_links(name): return None
